// Source review dates are editorial checkpoints, not dynamically generated dates.
export const reviewedOn = "2026-09-06";
export const topicLabels = {
  children: "Children's privacy", healthcare: "Healthcare privacy",
  education: "Student privacy", consumer: "Consumer privacy",
  financial: "Financial privacy", government: "Government records",
};

export const laws = [
  {
    id: "coppa", name: "Children's Online Privacy Protection Act & Rule", acronym: "COPPA",
    jurisdiction: "Federal", topics: ["children", "consumer"], kind: "Statute and regulation",
    citation: "15 U.S.C. 6501-6506; 16 CFR Part 312",
    summary: "Protects personal information collected online from children under 13. Covered services must explain their practices, obtain verifiable parental consent where required, and give parents review and deletion rights.",
    appliesTo: "Commercial child-directed websites and online services, and other covered operators with actual knowledge that they collect personal information from children under 13.",
    points: ["The amended rule addresses separate consent for certain third-party disclosures, including targeted advertising.", "Operators must maintain information-security and data-retention policies. Exceptions to parental consent are limited."],
    status: "In effect. The FTC's 2025 amendments have a general compliance date of April 22, 2026; see the current rule and agency guidance for specific provisions.",
    credit: "Enacted by the U.S. Congress; implementing rule issued by the Federal Trade Commission (FTC).",
    text: [{label: "Full COPPA Rule - 16 CFR Part 312", url: "https://www.ecfr.gov/current/title-16/chapter-I/subchapter-C/part-312", publisher: "Office of the Federal Register / Government Publishing Office (eCFR)"}, {label: "COPPA statute - 15 U.S.C. Chapter 91", url: "https://uscode.house.gov/view.xhtml?path=/prelim@title15/chapter91&edition=prelim", publisher: "U.S. House Office of the Law Revision Counsel"}],
    references: [{label: "FTC: Six-step COPPA compliance plan (updated May 2026)", url: "https://www.ftc.gov/business-guidance/resources/childrens-online-privacy-protection-rule-six-step-compliance-plan-your-business"}],
    excerpt: {text: "Child means an individual under the age of 13.", citation: "16 CFR 312.2", url: "https://www.ecfr.gov/current/title-16/chapter-I/subchapter-C/part-312#p-312.2(Child)"},
  },
  {
    id: "hipaa-privacy", name: "HIPAA Privacy Rule", acronym: "HIPAA",
    jurisdiction: "Federal", topics: ["healthcare", "children"], kind: "Regulation",
    citation: "45 CFR Parts 160 and 164, Subparts A and E",
    summary: "Sets limits on the use and disclosure of protected health information and gives patients rights to access records, request corrections, and receive information about privacy practices.",
    appliesTo: "Covered health plans, healthcare clearinghouses, qualifying healthcare providers, and business associates where specified. It does not cover every health app or every holder of health information.",
    points: ["Parents often act as personal representatives, but state minor-consent laws and other exceptions can limit parental access.", "The rule permits specified disclosures without authorization, including many treatment, payment, and healthcare-operations uses."],
    status: "Core rule in effect. Some 2024 reproductive-health amendments were vacated by a court in June 2025; check HHS's court-order notice before relying on those provisions.",
    credit: "Issued by the U.S. Department of Health and Human Services (HHS) under legislation enacted by the U.S. Congress.",
    text: [{label: "Privacy standards - 45 CFR Part 164, Subpart E", url: "https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C/part-164/subpart-E", publisher: "Office of the Federal Register / GPO (eCFR)"}, {label: "General provisions - 45 CFR Part 160", url: "https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C/part-160", publisher: "Office of the Federal Register / GPO (eCFR)"}],
    references: [{label: "HHS: Summary of the Privacy Rule", url: "https://www.hhs.gov/hipaa/for-professionals/privacy/laws-regulations/index.html"}, {label: "HHS: Reproductive health rule and court-order updates", url: "https://www.hhs.gov/hipaa/for-professionals/special-topics/reproductive-health/index.html"}],
  },
  {
    id: "hipaa-security", name: "HIPAA Security Rule", acronym: "HIPAA",
    jurisdiction: "Federal", topics: ["healthcare"], kind: "Regulation",
    citation: "45 CFR Part 164, Subpart C",
    summary: "Requires administrative, physical, and technical safeguards for electronic protected health information. Risk analysis, access controls, workforce practices, and contingency planning are central obligations.",
    appliesTo: "HIPAA covered entities and business associates that create, receive, maintain, or transmit electronic protected health information.",
    points: ["Safeguards protect confidentiality, integrity, and availability of electronic records.", "A proposed rule is not itself an enforceable final rule. Consult the current codified requirements alongside HHS rulemaking updates."],
    status: "Existing security standards are in effect. HHS separately lists its cybersecurity modernization proposal; proposed requirements are not presented here as current obligations.",
    credit: "Issued by HHS under legislation enacted by the U.S. Congress.",
    text: [{label: "Full Security Rule - 45 CFR Part 164, Subpart C", url: "https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C/part-164/subpart-C", publisher: "Office of the Federal Register / GPO (eCFR)"}],
    references: [{label: "HHS: Summary of the Security Rule", url: "https://www.hhs.gov/hipaa/for-professionals/security/laws-regulations/index.html"}, {label: "HHS: Security Rule proposal", url: "https://www.hhs.gov/hipaa/for-professionals/security/hipaa-security-rule-nprm/index.html"}],
  },
  {
    id: "hipaa-breach", name: "HIPAA Breach Notification Rule", acronym: "HIPAA / HITECH",
    jurisdiction: "Federal", topics: ["healthcare"], kind: "Regulation",
    citation: "45 CFR 164.400-414",
    summary: "Requires notices after a breach of unsecured protected health information. Depending on the circumstances, notices go to affected individuals, HHS, and the media; business associates notify covered entities.",
    appliesTo: "HIPAA covered entities and business associates handling unsecured protected health information.",
    points: ["Individual notices are due without unreasonable delay and generally no later than 60 days after discovery.", "HHS reporting schedules differ for breaches affecting fewer than 500 people. Definitions, risk assessments, and exceptions matter."],
    status: "In effect. Consult the rule for reporting thresholds, notice contents, and permitted delays.",
    credit: "Issued by HHS to implement breach-notification provisions of the HITECH Act, enacted by the U.S. Congress.",
    text: [{label: "Full Breach Notification Rule - Subpart D", url: "https://www.ecfr.gov/current/title-45/subtitle-A/subchapter-C/part-164/subpart-D", publisher: "Office of the Federal Register / GPO (eCFR)"}],
    references: [{label: "HHS: Breach Notification Rule guidance", url: "https://www.hhs.gov/hipaa/for-professionals/breach-notification/index.html"}],
  },
  {
    id: "part-2", name: "Confidentiality of Substance Use Disorder Patient Records", acronym: "42 CFR Part 2",
    jurisdiction: "Federal", topics: ["healthcare", "children"], kind: "Regulation",
    citation: "42 U.S.C. 290dd-2; 42 CFR Part 2",
    summary: "Provides special confidentiality protections for identifying substance-use-disorder records from covered programs. Consent, redisclosure, and use of records in legal proceedings have specific rules.",
    appliesTo: "Federally assisted Part 2 programs and certain recipients of their records. It does not automatically cover all mental-health or substance-use information.",
    points: ["The 2024 final rule aligns selected consent and redisclosure provisions with HIPAA while retaining special protections.", "The rules address minor patients and require breach notifications for unsecured Part 2 records."],
    status: "2024 final rule effective April 16, 2024; compliance required by February 16, 2026.",
    credit: "Issued by HHS under the confidentiality statute and CARES Act amendments enacted by the U.S. Congress.",
    text: [{label: "Full regulations - 42 CFR Part 2", url: "https://www.ecfr.gov/current/title-42/chapter-I/subchapter-A/part-2", publisher: "Office of the Federal Register / GPO (eCFR)"}],
    references: [{label: "HHS: Understanding Part 2 and its 2026 requirements", url: "https://www.hhs.gov/hipaa/part-2/index.html"}],
  },
  {
    id: "ftc-health-breach", name: "FTC Health Breach Notification Rule", acronym: "HBNR",
    jurisdiction: "Federal", topics: ["healthcare", "consumer"], kind: "Regulation",
    citation: "16 CFR Part 318",
    summary: "Requires covered personal-health-record businesses to notify consumers and the FTC after breaches of unsecured identifying health information, with media notification in specified cases.",
    appliesTo: "Vendors of personal health records, PHR-related entities, and their third-party service providers covered by the rule, generally outside HIPAA. Certain health apps and connected technologies qualify.",
    points: ["Unauthorized disclosures can qualify as breaches; hacking is not the only trigger.", "Coverage depends on the rule's definitions, including what constitutes a personal health record."],
    status: "In effect; the 2024 amendments took effect July 29, 2024.",
    credit: "Issued by the FTC under the HITECH Act, enacted by the U.S. Congress.",
    text: [{label: "Full rule - 16 CFR Part 318", url: "https://www.ecfr.gov/current/title-16/chapter-I/subchapter-C/part-318", publisher: "Office of the Federal Register / GPO (eCFR)"}],
    references: [{label: "FTC: Health Breach Notification Rule basics", url: "https://www.ftc.gov/business-guidance/resources/health-breach-notification-rule-basics-business"}],
  },
  {
    id: "ferpa", name: "Family Educational Rights and Privacy Act", acronym: "FERPA",
    jurisdiction: "Federal", topics: ["children", "education"], kind: "Statute and regulation",
    citation: "20 U.S.C. 1232g; 34 CFR Part 99",
    summary: "Protects education records at covered schools. Parents and eligible students can inspect records, seek amendments, and control many disclosures of personally identifiable information.",
    appliesTo: "Educational agencies and institutions receiving funds under programs administered by the U.S. Department of Education.",
    points: ["Rights transfer to the student at age 18 or upon attendance at a postsecondary institution at any age.", "Consent has exceptions, including certain school-official disclosures. School health records may be education records subject to FERPA."],
    status: "In effect. Coverage and disclosure exceptions are set out in the statute and implementing regulations.",
    credit: "Enacted by the U.S. Congress; regulations issued by the U.S. Department of Education.",
    text: [{label: "Full implementing regulations - 34 CFR Part 99", url: "https://studentprivacy.ed.gov/ferpa", publisher: "U.S. Department of Education"}, {label: "FERPA statute - 20 U.S.C. 1232g", url: "https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title20-section1232g&num=0&edition=prelim", publisher: "U.S. House Office of the Law Revision Counsel"}],
    references: [{label: "Department of Education: Student privacy FAQs", url: "https://studentprivacy.ed.gov/frequently-asked-questions"}],
  },
  {
    id: "ppra", name: "Protection of Pupil Rights Amendment", acronym: "PPRA",
    jurisdiction: "Federal", topics: ["children", "education"], kind: "Statute",
    citation: "20 U.S.C. 1232h",
    summary: "Protects students and parents in specified surveys, evaluations, marketing activities, and examinations. Its eight protected survey areas include mental health, religious beliefs, and certain family information.",
    appliesTo: "Programs and activities of education agencies and other recipients of U.S. Department of Education funds, with requirements depending on funding and activity.",
    points: ["Prior written parental consent applies to required, Department-funded surveys involving protected information.", "Other covered activities can require notice, opportunities to opt out, and parental inspection. Rights transfer at 18 or emancipation."],
    status: "In effect. Consent and opt-out obligations differ by activity; consult the complete statute.",
    credit: "Enacted by the U.S. Congress; administered by the U.S. Department of Education.",
    text: [{label: "Full statute - 20 U.S.C. 1232h", url: "https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title20-section1232h&num=0&edition=prelim", publisher: "U.S. House Office of the Law Revision Counsel"}],
    references: [{label: "Department of Education: What is PPRA?", url: "https://studentprivacy.ed.gov/faq/what-protection-pupil-rights-amendment-ppra"}, {label: "Department of Education: Student privacy FAQs", url: "https://studentprivacy.ed.gov/frequently-asked-questions"}],
  },
  {
    id: "ccpa", name: "California Consumer Privacy Act, as amended by CPRA", acronym: "CCPA / CPRA",
    jurisdiction: "California", topics: ["consumer", "children"], kind: "Statute",
    citation: "California Civil Code 1798.100-1798.199.100",
    summary: "Gives California consumers rights to know, delete, and correct personal information, opt out of sale or sharing, and limit certain uses of sensitive information, subject to exceptions.",
    appliesTo: "Businesses meeting statutory coverage thresholds and other entities with specified duties. Exemptions apply, including for certain health information; HIPAA does not create a universal business-wide exemption.",
    points: ["Sale or sharing of information of consumers known to be under 16 generally requires affirmative authorization; a parent or guardian authorizes for children under 13.", "CPRA amended the CCPA. They are presented together to avoid treating them as unrelated privacy regimes."],
    status: "In effect. Regulations and later amendments have their own operative dates; check the agency's current regulations alongside the statute.",
    credit: "CCPA enacted by the California Legislature; CPRA adopted by California voters as Proposition 24.",
    text: [{label: "Full CCPA statute, as amended", url: "https://leginfo.legislature.ca.gov/faces/codes_displayText.xhtml?division=3.&part=4.&lawCode=CIV&title=1.81.5.", publisher: "California Legislative Information"}],
    references: [{label: "California Attorney General: CCPA rights and exceptions", url: "https://oag.ca.gov/privacy/ccpa"}, {label: "CalPrivacy: Current laws and regulations", url: "https://privacy.ca.gov/laws-and-regulations/"}],
  },
  {
    id: "wa-health", name: "Washington My Health My Data Act", acronym: "MHMDA",
    jurisdiction: "Washington", topics: ["healthcare", "consumer"], kind: "Statute",
    citation: "Chapter 19.373 RCW",
    summary: "Protects consumer health data beyond HIPAA, including certain health inferences. It establishes privacy notices, consent requirements, deletion rights, and separate authorization for sales.",
    appliesTo: "Covered businesses serving Washington consumers, including qualifying out-of-state entities. The statute contains data-specific exemptions and special rules for certain activities.",
    points: ["Certain geofencing around healthcare facilities is prohibited.", "Enforcement operates through Washington's Consumer Protection Act, including qualifying private actions."],
    status: "In effect. Core requirements began March 31, 2024, or June 30, 2024 for small businesses; the geofencing prohibition began July 23, 2023.",
    credit: "Enacted by the Washington State Legislature and signed by the Governor in 2023.",
    text: [{label: "Full act - Chapter 19.373 RCW", url: "https://app.leg.wa.gov/RCW/default.aspx?cite=19.373&full=true", publisher: "Washington State Legislature"}],
    references: [{label: "Washington Attorney General: My Health My Data FAQs", url: "https://www.atg.wa.gov/protecting-washingtonians-personal-health-data-and-privacy"}],
  },
  {
    id: "cmia", name: "California Confidentiality of Medical Information Act", acronym: "CMIA",
    jurisdiction: "California", topics: ["healthcare"], kind: "Statute",
    citation: "California Civil Code, Division 1, Part 2.6 (56 et seq.)",
    summary: "Restricts disclosure of medical information by covered parties and sets authorization and confidentiality requirements. Permitted and mandatory disclosures are specified in the law.",
    appliesTo: "Covered healthcare providers, health plans, contractors, and other entities defined by the statute, including certain businesses maintaining medical information.",
    points: ["California protections can apply alongside HIPAA.", "Definitions and exceptions are essential: not every disclosure requires a new patient authorization."],
    status: "In effect, as amended. Consult all relevant chapters of Part 2.6, not only the definitions.",
    credit: "Enacted and amended by the California Legislature.",
    text: [{label: "CMIA - Part 2.6 (browse its chapters)", url: "https://leginfo.legislature.ca.gov/faces/codes_displayexpandedbranch.xhtml?tocCode=CIV&division=1.&title=&part=2.6.&chapter=&article=", publisher: "California Legislative Information"}, {label: "Disclosure restrictions - Civil Code 56.10", url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?lawCode=CIV&sectionNum=56.10.", publisher: "California Legislative Information"}],
    references: [{label: "CMIA definitions - Civil Code 56.05", url: "https://leginfo.legislature.ca.gov/faces/codes_displayText.xhtml?division=1.&chapter=1.&part=2.6.&lawCode=CIV"}],
  },
  {
    id: "sopipa", name: "K-12 Pupil Online Personal Information Protection Act", acronym: "SOPIPA (formerly Student Online Personal Information Protection Act)",
    jurisdiction: "California", topics: ["children", "education"], kind: "Statute",
    citation: "California Business and Professions Code 22584-22585",
    summary: "Limits how covered K-12 online services use student information, including restrictions on targeted advertising, non-school profiling, sales, and disclosures.",
    appliesTo: "Operators with actual knowledge that their site, service, or application is used primarily for K-12 school purposes and was designed and marketed for those purposes.",
    points: ["Covered operators must use reasonable security practices and delete covered information when requested by the school or district.", "Specified educational, research, service-provider, and other uses are permitted; general-audience services are treated differently."],
    status: "Operative since January 1, 2016, as amended. The chapter heading was renamed in 2024. Section 22584 contains requirements and exceptions; section 22585 sets the original operative date.",
    credit: "Enacted by the California Legislature.",
    text: [{label: "Requirements - BPC 22584", url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=22584.&lawCode=BPC", publisher: "California Legislative Information"}, {label: "Operative date - BPC 22585", url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=22585.&lawCode=BPC", publisher: "California Legislative Information"}],
    references: [{label: "California Legislature: SOPIPA statutory requirements", url: "https://leginfo.legislature.ca.gov/faces/codes_displaySection.xhtml?sectionNum=22584.&lawCode=BPC"}],
  },
  {
    id: "privacy-act", name: "Privacy Act of 1974", acronym: "Privacy Act",
    jurisdiction: "Federal", topics: ["government"], kind: "Statute",
    citation: "5 U.S.C. 552a",
    summary: "Governs federal agencies' handling of personal information in systems of records. It establishes access and amendment rights and limits disclosure, subject to statutory exceptions and exemptions.",
    appliesTo: "Federal agency systems of records retrieved by a person's name or other identifying particular. Statutory individual rights generally cover U.S. citizens and lawful permanent residents, with some extensions under other law.",
    points: ["Agencies publish system-of-records notices explaining their records and uses.", "This is not a general privacy law for every private business or state agency."],
    status: "In effect, as amended. System-specific notices, routine uses, and exemptions affect particular records.",
    credit: "Enacted by the U.S. Congress; administered by federal agencies for their records.",
    text: [{label: "Full Privacy Act - 5 U.S.C. 552a", url: "https://uscode.house.gov/view.xhtml?req=granuleid:USC-prelim-title5-section552a&num=0&edition=prelim", publisher: "U.S. House Office of the Law Revision Counsel"}],
    references: [{label: "U.S. Department of Justice: Privacy Act overview and resources", url: "https://www.justice.gov/opcl/privacy-act-1974"}],
  },
  {
    id: "glba", name: "Gramm-Leach-Bliley Act: Financial Privacy", acronym: "GLBA",
    jurisdiction: "Federal", topics: ["financial", "consumer"], kind: "Statute and regulations",
    citation: "15 U.S.C. 6801-6809; FTC rules at 16 CFR Parts 313 and 314",
    summary: "Requires covered financial institutions to explain information-sharing practices and safeguard customer information. Certain disclosures to nonaffiliated third parties carry notice and opt-out requirements.",
    appliesTo: "Financial institutions as defined in the law. The applicable regulator and implementing rules depend on the institution and activity; the FTC's rules do not cover every financial institution.",
    points: ["Privacy notices and disclosure exceptions are addressed separately from security safeguards.", "The FTC Safeguards Rule includes a written security program and reporting duties for qualifying security events."],
    status: "In effect, as amended. Use the rules of the regulator with jurisdiction over the institution.",
    credit: "Enacted by the U.S. Congress; implemented by the FTC and other financial regulators within their jurisdictions.",
    text: [{label: "Financial privacy statute - 15 U.S.C. Chapter 94", url: "https://uscode.house.gov/view.xhtml?path=/prelim@title15/chapter94&edition=prelim", publisher: "U.S. House Office of the Law Revision Counsel"}, {label: "FTC Financial Privacy Rule - Part 313", url: "https://www.ecfr.gov/current/title-16/chapter-I/subchapter-C/part-313", publisher: "Office of the Federal Register / GPO (eCFR)"}, {label: "FTC Safeguards Rule - Part 314", url: "https://www.ecfr.gov/current/title-16/chapter-I/subchapter-C/part-314", publisher: "Office of the Federal Register / GPO (eCFR)"}],
    references: [{label: "FTC: Gramm-Leach-Bliley Act guidance", url: "https://www.ftc.gov/business-guidance/privacy-security/gramm-leach-bliley-act"}, {label: "FTC: Safeguards Rule business guidance", url: "https://www.ftc.gov/business-guidance/resources/ftc-safeguards-rule-what-your-business-needs-know"}],
  },
];

export function searchLaws(query = "", topic = "all", jurisdiction = "all") {
  const normalize = (value) => value.normalize("NFKD").replace(/[\u0300-\u036f]/g, "").toLowerCase().replace(/[^a-z0-9]+/g, " ").trim();
  const terms = normalize(query).split(/\s+/).filter(Boolean);
  return laws.filter((law) => {
    const searchable = normalize([law.name, law.acronym, law.jurisdiction, law.citation, law.summary, law.appliesTo, ...law.points, ...law.topics.map((topic) => topicLabels[topic])].join(" "));
    return (topic === "all" || law.topics.includes(topic)) &&
      (jurisdiction === "all" || law.jurisdiction === jurisdiction) &&
      terms.every((term) => searchable.includes(term));
  });
}
